version: "3"

services:
  mongodb_database:
    container_name: "gym-mongo"
    image: bitnami/mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_USER=${MONGODB_ROOT_USER}
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    volumes:
      - gym_mongo_data:/bitnami/mongodb
    restart: unless-stopped

volumes:
  gym_mongo_data:
